// <auto-generated />
using Mec126.Models.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mec126.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260515144200_SeedProducts")]
    partial class SeedProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mec126.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Electronics",
                            Description = "High performance laptop for gaming and development.",
                            Name = "Gaming Laptop",
                            Price = 1200.99m
                        },
                        new
                        {
                            Id = 2,
                            Category = "Electronics",
                            Description = "Noise cancelling over-ear wireless headphones.",
                            Name = "Wireless Headphones",
                            Price = 149.50m
                        },
                        new
                        {
                            Id = 3,
                            Category = "Furniture",
                            Description = "Ergonomic office chair with lumbar support.",
                            Name = "Office Chair",
                            Price = 320.00m
                        },
                        new
                        {
                            Id = 4,
                            Category = "Accessories",
                            Description = "RGB mechanical keyboard with blue switches.",
                            Name = "Mechanical Keyboard",
                            Price = 89.99m
                        },
                        new
                        {
                            Id = 5,
                            Category = "Wearables",
                            Description = "Fitness tracking smart watch with AMOLED display.",
                            Name = "Smart Watch",
                            Price = 210.75m
                        },
                        new
                        {
                            Id = 6,
                            Category = "Home Appliances",
                            Description = "Automatic coffee maker with timer feature.",
                            Name = "Coffee Maker",
                            Price = 65.25m
                        },
                        new
                        {
                            Id = 7,
                            Category = "Sports",
                            Description = "Lightweight running shoes for daily workouts.",
                            Name = "Running Shoes",
                            Price = 95.00m
                        },
                        new
                        {
                            Id = 8,
                            Category = "Electronics",
                            Description = "Portable waterproof Bluetooth speaker.",
                            Name = "Bluetooth Speaker",
                            Price = 55.49m
                        },
                        new
                        {
                            Id = 9,
                            Category = "Bags",
                            Description = "Durable backpack suitable for travel and work.",
                            Name = "Backpack",
                            Price = 40.00m
                        },
                        new
                        {
                            Id = 10,
                            Category = "Furniture",
                            Description = "LED desk lamp with adjustable brightness.",
                            Name = "Desk Lamp",
                            Price = 27.99m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
